name: Build Application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      java-version:
        description: 'Java version'
        default: '17'
        type: string
      build-command:
        description: 'Build command'
        default: 'mvn -B clean verify'
        type: string

jobs:
  java-build:
    uses: euthiagodealmeida/conveyor-actions/.github/workflows/java-workflow.yml@develop
    with:
      java-version: ${{ github.event.inputs.java-version }}
      build-command: ${{ github.event.inputs.build-command }}
      fetch-depth: '1'
      lfs: 'false'
      submodules: 'false'
