name: Build, Test and Package application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    
    
jobs:
  CI:
    uses: euthiagodealmeida/conveyor-actions/.github/workflows/orchestrator.yml@develop
    with:
      java-distribution: 'temurin'
      java-version: 17
      # build-command: ${{ github.event.inputs.build-command }}
      artifact-name: 'petclinic-artifact'
      artifact-path: 'target'
      fetch-depth: '1'
      lfs: 'false'
      submodules: 'false'

